### PR TITLE
Syntax Updated with Py3

### LINKED ISSUE #89: convert all contributions to python 3.8 syntax
There are few contributions which still include python 2.7 syntax, which needs to be converted to python 3.8 syntax

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com 
* [x] Does your filename follow the naming Conventions?
* [x] Have you linked your PR to an Issue?

### Changes:
- [x] Syntax Updated ( python 2 -> Python 3 )
- [x] Code Formatted
- [x] Minor Errors, Bugs Fixed

**Closing issues**

closes #89

### CODE REVIEW

**Review by adityaarakeri — APPROVED** [review]
looks good

**Comment by adityaarakeri** [comment]
resolve all the conflicts

**Comment by Siddhant-K-code** [comment]
@adityaarakeri if anything left ? please point it out, and if not, pls merge.

**Comment by adityaarakeri** [comment]
@Siddhant-K-code rebase your PR with the master branch and you should be able to resolve the merge conflicts

**Comment by Siddhant-K-code** [comment]
@adityaarakeri It will be fixed when you will merge it. it is very difficult to push it from master branch

**Comment by adityaarakeri** [comment]
> @adityaarakeri It will be fixed when you will merge it. it is very difficult to push it from master branch

It does not allow me to merge with merge conflicts. 
refer this if you dont know how to resolve - >https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line

**Comment by Siddhant-K-code** [comment]
check if you can merge it ? @adityaarakeri

**Comment by adityaarakeri** [comment]
@Siddhant-K-code please resolve merge conflicts, only then i can merge this.

**Comment by Siddhant-K-code** [comment]
I don't know why, but I didn't even edit the file which has conflicts

**Comment by Siddhant-K-code** [comment]
image
I think it has a lot of conflicts

**Comment by Siddhant-K-code** [comment]
please check #102

**Comment by adityaarakeri** [comment]
@Siddhant-K-code again i cannot merge if there are conflicts.

**Comment by Siddhant-K-code** [comment]
@adityaarakeri #102  has no conflicts

**Pull request closed without merging**
