### PR TITLE
Add bin tree height riddle ( #87 )

### LINKED ISSUE #87: riddle: find height of a binary tree
the riddle is: find the height (longest path from the root node) of a binary tree (not necessarily balanced).

### PR DESCRIPTION
**Pull request by sharpblade4**
**IMPORTANT: Please do not create a Pull Request without an issue.**

closes #87 

### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com  [irrelevant]
* [x] Does your filename follow the naming Conventions?
* [x] Have you linked your PR to an Issue?

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by sharpblade4** [comment]
@adityaarakeri  any idea why I'm failing the CI? (it seems that the build fails on unrelated component, something that I didn't change)

**Review by adityaarakeri — CHANGES_REQUESTED** [review]
Could you please rename your folder with out spaces

**Comment by sharpblade4** [comment]
> Could you please rename your folder with out spaces

@adityaarakeri  I didn't make this folder, it already has older code in it. I was just sticking to the current structure.

**Review by adityaarakeri — APPROVED** [review]

**Comment by adityaarakeri** [comment]
> > Could you please rename your folder with out spaces
> 
> @adityaarakeri I didn't make this folder, it already has older code in it. I was just sticking to the current structure.
> 
> Note that I already fixed a bug in the repository (unrelated to my contribution) and I want to avoid spending more time on minor global-repo issues.
> 
> EDIT: nvm, I just did it..

Thanks @sharpblade4

**Pull request merged**
