### PR TITLE
added finding kth smallest element in an array algorithm

### PR DESCRIPTION
**Pull request by Sarthakbh321**
You are given an array of integers, and you have to find the k-th smallest number in the array.
**Input Format**
The first line contains the value of K
The second line contains a space separated list of integers

**Output Format**
The only line contains the k-th smallest number in the array

Example:
**Input**
3
7 10 4 3 20 15

**Output**
7

### CODE REVIEW

**Comment by adityaarakeri** [comment]
Thanks for the PR 👍

**Comment by Sarthakbh321** [comment]
I have updated the initial comment

**Comment by adityaarakeri** [comment]
Thanks for updating with comments, one last thing: could you please rebase master?

**Comment by Sarthakbh321** [comment]
Done

**Comment by adityaarakeri** [comment]
> You are given an array of integers, and you have to find the k-th smallest number in the array.
> **Input Format**
> The first line contains the value of K
> The second line contains a space separated list of integers
> 
> **Output Format**
> The only line contains the k-th smallest number in the array
> 
> Example:
> **Input**
> 3
> 7 10 4 3 20 15
> 
> **Output**
> 7

@Sarthakbh321 few more changes
- The above details needs to be added to the actual script file
- rebase and push to master
everything else looks good 👍

**Comment by Sarthakbh321** [comment]
Updated the script and rebased master

**Pull request merged**
